sqlc-gen:
	sqlc generate
db-migrate-up:
	go run ./cmd/migrate up
db-migrate-up-last:
	go run ./cmd/migrate up-last
db-migrate-down:
	go run ./cmd/migrate down
db-migrate-down-first:
	go run ./cmd/migrate down-first
db-generate:
	sqlc generate
init-data:
	go run ./cmd/init_data