// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package repository

import (
	"context"
)

// iteratorForAddStockRatings implements pgx.CopyFromSource.
type iteratorForAddStockRatings struct {
	rows                 []AddStockRatingsParams
	skippedFirstNextCall bool
}

func (r *iteratorForAddStockRatings) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForAddStockRatings) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Ticker,
		r.rows[0].Company,
		r.rows[0].Brokerage,
		r.rows[0].TargetFrom,
		r.rows[0].TargetTo,
		r.rows[0].Action,
		r.rows[0].RawAction,
		r.rows[0].RatingFrom,
		r.rows[0].RawRatingFrom,
		r.rows[0].RatingTo,
		r.rows[0].RawRatingTo,
		r.rows[0].At,
	}, nil
}

func (r iteratorForAddStockRatings) Err() error {
	return nil
}

func (q *Queries) AddStockRatings(ctx context.Context, arg []AddStockRatingsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"stock_rating"}, []string{"ticker", "company", "brokerage", "target_from", "target_to", "action", "raw_action", "rating_from", "raw_rating_from", "rating_to", "raw_rating_to", "at"}, &iteratorForAddStockRatings{rows: arg})
}
