// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type RawStockRating struct {
	ID         uuid.UUID
	Ticker     string
	TargetFrom string
	TargetTo   string
	Company    string
	Action     string
	Brokerage  string
	RatingFrom string
	RatingTo   string
	At         time.Time
}

type StockRating struct {
	ID         uuid.UUID
	Ticker     string
	Company    string
	TargetFrom pgtype.Numeric
	TargetTo   pgtype.Numeric
	Action     string
	RatingFrom string
	RatingTo   string
	At         time.Time
}
