// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: raw-stock-rating.sql

package repository

import (
	"context"
	"time"
)

type AddRawStockRatingsParams struct {
	Ticker     string
	TargetFrom string
	TargetTo   string
	Company    string
	Action     string
	Brokerage  string
	RatingFrom string
	RatingTo   string
	At         time.Time
}

const clearRawStockRating = `-- name: ClearRawStockRating :exec
TRUNCATE TABLE raw_stock_rating
`

func (q *Queries) ClearRawStockRating(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearRawStockRating)
	return err
}
