// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: raw-stock-ratings.sql

package repository

import (
	"context"
	"time"
)

type AddRawStockRatingsParams struct {
	Ticker     string
	TargetFrom string
	TargetTo   string
	Company    string
	Action     string
	Brokerage  string
	RatingFrom string
	RatingTo   string
	At         time.Time
}

const deleteRawStockRatings = `-- name: DeleteRawStockRatings :exec
TRUNCATE TABLE raw_stock_ratings
`

func (q *Queries) DeleteRawStockRatings(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteRawStockRatings)
	return err
}
