// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stock-events.sql

package repository

import (
	"context"
	"time"
)

const addStockEvents = `-- name: AddStockEvents :exec
INSERT INTO stock_events (
    ticker, target_from, target_to, company, action, brokerage, rating_from, rating_to, at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
`

type AddStockEventsParams struct {
	Ticker     string
	TargetFrom string
	TargetTo   string
	Company    string
	Action     string
	Brokerage  string
	RatingFrom string
	RatingTo   string
	At         time.Time
}

func (q *Queries) AddStockEvents(ctx context.Context, arg AddStockEventsParams) error {
	_, err := q.db.ExecContext(ctx, addStockEvents,
		arg.Ticker,
		arg.TargetFrom,
		arg.TargetTo,
		arg.Company,
		arg.Action,
		arg.Brokerage,
		arg.RatingFrom,
		arg.RatingTo,
		arg.At,
	)
	return err
}
