// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stock-rating.sql

package repository

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AddStockRatingsParams struct {
	Ticker     string
	Company    string
	TargetFrom pgtype.Numeric
	TargetTo   pgtype.Numeric
	Action     StockActionType
	RatingFrom StockRatingType
	RatingTo   StockRatingType
	At         time.Time
}

const clearStockRating = `-- name: ClearStockRating :exec
TRUNCATE TABLE stock_rating
`

func (q *Queries) ClearStockRating(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearStockRating)
	return err
}
