// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stock-events.sql

package repository

import (
	"context"
	"time"
)

type AddStockEventsParams struct {
	Ticker     string
	TargetFrom string
	TargetTo   string
	Company    string
	Action     string
	Brokerage  string
	RatingFrom string
	RatingTo   string
	At         time.Time
}

const deleteAllStockEvents = `-- name: DeleteAllStockEvents :exec
TRUNCATE TABLE stock_events
`

func (q *Queries) DeleteAllStockEvents(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllStockEvents)
	return err
}
